services:
  - type: web
    name: solve-innovate-backend
    env: docker
    repo: https://github.com/224Abhay/Solve-Innovate
    rootDir: fastapi
    plan: free # or starter
    healthCheckPath: /docs
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: LLM
        value: openai
      - key: IMAGE_PROVIDER
        value: dall-e-3
      - key: APP_DATA_DIRECTORY
        value: /app/app_data
    disk:
      name: app-data
      mountPath: /app/app_data
      sizeGB: 1
